#cloud-config

package_update: true
package_upgrade: true
repo_update: true
repo_upgrade: true

users:
  - default
  - name: appuser
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCo+2u6kEzztL+yh8kinf1q9P+1GgKXbUck9jYlApVN6NY8YhJm4MO/bfq1V6BYHUBU92q0FyalxTYePj/6BuO28KlE6zNvlaaVrZCTYArVpLr3tJqeExX4t+LuKdYjiICJVzo64u6b3SAY6zjmbt/zsp1/8j7EDKUEF5cSxaCpeJO9WY2SkGcKJ4amzsdsv5Pnwa1yrhdYprdIXFCPLMkNThk/9TgV4m8ljQD/Cl9iwmI5SpQjdlfip5CMd8B6QmTXv2bvOD8GGNkKQg9dT86BJbIeMkWeUcfZhgb9Dyg1qHqx6++w4hAN5mZs5/8bc3faY4ml57gl0sAD1CyZ3bAQKTRvgqV5Os+Iz5zMuGvgnxhxLxpJlLfR3+pSbs9sqYIHumGVivXTHoGWSkUbSbfsjdDdSsYYLScOHlBOubQdfTDBGnWrhuUF/7SvbeTbj9jtCYTYOGcCikms3PuJaK8eUYVBBbrWsWRGkEEFi2SqU0oHQIT5I5GsG9RliTan/hU= appuser'
packages:
  - apt-transport-https
  - ca-certificates
  - ruby-full
  - ruby-bundler
  - build-essential
  - mongodb-org
  - git